export type ProductType = {
  name: string;
  surname: string;
  price: string;
  desc: string;
  link: string;
  release: string;
  platforms: string;
  genre: string;
  developers: string;
  publishers: string;
  inCart: boolean;
  selected: boolean;
  isHovered: boolean;
  isLiked: boolean;
  rating: number;
  id: number;
  cover: string;
  footage: string[];
};
